version: '3.8'

services:
  greenplum:
    container_name: greenplum
    image: datagrip/greenplum:6.8
    hostname: greenplum
    environment:
      - GREENPLUM_USER=gpadmin
      - GREENPLUM_PASSWORD=gpadmin
    ports:
      - "5432:5432"
    stdin_open: true
    tty: true
    networks:
      - greenplum_net
    volumes:
      - greenplum_data:/data
      - ./gpconfigs:/home/gpadmin/configs

networks:
  greenplum_net:
    driver: bridge

volumes:
  greenplum_data:
